---
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: onexidz
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
geodata-mode: true
geodata-loader: memconservative
global-client-fingerprint: chrome
keep-alive-interval: 15
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  proxy-server-nameserver:
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - https://dns.google/dns-query
  fallback:
    - 8.8.4.4
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
  respect-rules: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
proxy-groups:
- name: Auto-ID_MIX
  type: fallback
  disable-udp: false
  use:
  - ID
  - MIX
  url: http://www.gstatic.com/generate_204
  interval: '100'
  tolerance: '50'
- name: Load-MIX_ID
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - MIX
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '100'
  tolerance: '50'
- name: Server-UMUM
  type: select
  disable-udp: false
  proxies:
  - Load-MIX_ID
  - Auto-ID_MIX
- name: Server-INDO
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
- name: Block-IKLAN
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Load-MIX_ID
  - Auto-ID_MIX
- name: Block-PORN
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Load-MIX_ID
- name: Server-GAME
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
  - Direct-Modem
- name: Direct-Modem
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - DIRECTMODEM
  url: http://cp.cloudflare.com/generate_204
  interval: 100
proxy-providers:
  ID:
    type: file
    path: "./proxy_provider/id.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  MIX:
    type: file
    path: "./proxy_provider/mix.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  DIRECTMODEM:
    type: file
    path: "./proxy_provider/directmodem.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
rule-providers:
  Umum:
    type: file
    behavior: classical
    path: "./rule_provider/umum.yaml"
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
  Indo:
    type: http
    path: "./rule_provider/indo.yaml"
    url: https://raw.githubusercontent.com/rtaserver/Clash-Rule-IP-Indo/main/rule-indo.yaml
    interval: 300
    proxy: Auto-ID_MIX
    behavior: classical
    format: yaml
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,123/136/137-139,Server-GAME,udp
- RULE-SET,Reject,Block-IKLAN
- AND,((NETWORK,udp),(OR,((DST-PORT,443),(GEOSITE,youtube)))),REJECT
- AND,((GEOSITE,oisd-full),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Block-IKLAN
- AND,((GEOSITE,rule-ads),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Block-IKLAN
- GEOSITE,oisd-nsfw,Block-PORN
- GEOIP,GOOGLE,Server-UMUM
- GEOSITE,GOOGLE,Server-UMUM
- AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Server-UMUM
- AND,((NETWORK,UDP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Server-UMUM
- GEOSITE,rule-gaming,Server-GAME
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,TCP)),Server-GAME
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,UDP)),Server-GAME
- GEOSITE,rule-indo,Server-INDO
- GEOSITE,rule-sosmed,Server-INDO
- GEOSITE,rule-streaming,Server-INDO
- GEOIP,id,Server-INDO
- GEOIP,facebook,Server-INDO
- GEOIP,netflix,Server-INDO
- GEOIP,telegram,Server-INDO
- GEOIP,twitter,Server-INDO
- RULE-SET,Indo,Server-INDO
- GEOSITE,rule-speedtest,Server-INDO
- AND,((RULE-SET,Umum),(NETWORK,TCP)),Server-UMUM
- AND,((RULE-SET,Umum),(NETWORK,UDP)),Server-UMUM
- MATCH,Server-UMUM
